import "./globals.css";
import Header from "./components/Header";
import { Poppins } from "next/font/google";
import { UserContextProvider } from "./hooks/UserContext";
const poppins = Poppins({
  weight: ["400", "600"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UserContextProvider>
          <Header />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
